### ISSUE TITLE
Jupyterhub Custom Image Error

### ISSUE THREAD

**Issue by aghilannara** [elixierdata/helm#4]
An error occured when installing the jupyterhub with any additional package. An example is including python package "tensorflow" for jupyterhub purpose. 

Steps to reproduce:
1. Install default elixier with default pvc
2. Uninstall containers (but leave pvc intact)
3. Install custom containers with `--set core_image.repository=<image-name> --set core_image.tag=<image-tag>`
4. kubectl logs jupyterhub-container will reveal error need perform `jupyterhub upgrade-db`  as per screenshot below

![image](https://user-images.githubusercontent.com/16127600/215411335-af00fdca-12f3-4f74-8253-284034572631.png)

**Comment by kagesenshi** [comment]
should be fixed in latest release
