### ISSUE TITLE
Pip cannot perform a '--user' install 

### ISSUE THREAD

**Issue by Nightbane112** [elixierdata/helm#6]
Users are unable to install additional python libs via Pip with following option as shown below:

![image](https://user-images.githubusercontent.com/5657994/229469397-5ccd2055-c079-4427-aa57-ac00f02d2f8c.png)

**Comment by aghilannara** [comment]
This issue can be closed? Since latest commit already fix this

**Comment by Nightbane112** [comment]
Closing issue with commit [8381c74](https://github.com/elixierco/elixier/commit/8381c74466aff37de858ca49c886682f44c9de4d).
